name: devhub_hrms
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.6.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dropdown_textfield: ^1.2.0
  equatable: ^2.0.5
  firebase_core: ^2.16.0
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.7.3
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  get_it: ^7.7.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^26.2.12
  share_plus: ^10.0.2
  rxdart: ^0.28.0
  url_launcher: ^6.3.0
  syncfusion_flutter_calendar: ^26.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/icon/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
